### ISSUE TITLE
av1 format no video

### ISSUE THREAD

**Issue by tazihad** [flathub/info.smplayer.SMPlayer#5] opened 2023-05-24 21:22 UTC
If I open av1 with smplayer. There's no video. Only audio. But smplayer from ubuntu-22.04 repo supports av1. can you look into it?

**Comment by smplayer-dev** [comment] 2023-05-27 17:26
I think it's fixed in this build: https://github.com/smplayer-dev/smplayer/releases/download/v22.7.0-10244/smplayer-22.7.0.10129-sdk5.15.flatpak
Could you test it?

**Comment by tazihad** [comment] 2023-05-27 18:16
> I think it's fixed in this build: https://github.com/smplayer-dev/smplayer/releases/download/v22.7.0-10244/smplayer-22.7.0.10129-sdk5.15.flatpak Could you test it?

I can't play any video with this build. Here's the log:
```
/app/bin/mpv --no-quiet --terminal --no-msg-color --input-ipc-server=/tmp/smplayer-mpv-2 --msg-level=ffmpeg/demuxer=error --video-rotate=no --no-config --no-fs --vd-lavc-threads=2 --hwdec=no --sub-auto=fuzzy --no-input-default-bindings --input-vo-keyboard=no --no-input-cursor --cursor-autohide=no --no-keepaspect --wid=104857674 --monitorpixelaspect=1 --osd-level=1 --osd-scale=1 --osd-bar-align-y=0.6 --sub-ass --embeddedfonts --sub-ass-line-spacing=0 --sub-scale=1 --sub-font=Arial --sub-color=#ffffff00 --sub-shadow-color=#ff000000 --sub-border-color=#ff000000 --sub-border-size=0.75 --sub-shadow-offset=2.5 --sub-font-size=50 --sub-bold=no --sub-italic=no --sub-margin-y=8 --sub-margin-x=20 --sub-codepage=ISO-8859-1 --vid=1 --sid=1 --sub-pos=100 --volume=100 --demuxer-max-bytes=102400000 --start=1394 --screenshot-template=cap_%F_%p_%02n --screenshot-format=jpg --screenshot-directory=/home/zihad/Pictures/smplayer_screenshots --audio-pitch-correction=yes --volume-max=100 --no-osd-bar --term-playing-msg=MPV_VERSION=${=mpv-version:}
INFO_VIDEO_WIDTH=${=width}
INFO_VIDEO_HEIGHT=${=height}
INFO_VIDEO_ASPECT=${=video-params/aspect}
INFO_VIDEO_FPS=${=container-fps:${=fps}}
INFO_VIDEO_FORMAT=${=video-format}
INFO_VIDEO_CODEC=${=video-codec}
INFO_DEMUX_ROTATION=${=track-list/0/demux-rotation}
INFO_AUDIO_FORMAT=${=audio-codec-name}
INFO_AUDIO_CODEC=${=audio-codec}
INFO_AUDIO_RATE=${=audio-params/samplerate}
INFO_AUDIO_NCH=${=audio-params/channel-count}
INFO_LENGTH=${=duration:${=length}}
INFO_DEMUXER=${=current-demuxer:${=demuxer}}
INFO_SEEKABLE=${=seekable}
INFO_TITLES=${=disc-titles}
INFO_CHAPTERS=${=chapters}
INFO_TRACKS_COUNT=${=track-list/count}
METADATA_TITLE=${metadata/by-key/title:}
METADATA_ARTIST=${metadata/by-key/artist:}
METADATA_ALBUM=${metadata/by-key/album:}
METADATA_GENRE=${metadata/by-key/genre:}
METADATA_DATE=${metadata/by-key/date:}
METADATA_TRACK=${metadata/by-key/track:}
METADATA_COPYRIGHT=${metadata/by-key/copyright:}
INFO_MEDIA_TITLE=${=media-title:}
INFO_STREAM_PATH=${stream-path}
 --audio-client-name=SMPlayer --term-status-msg=STATUS: ${=time-pos} / ${=duration:${=length:0}} P: ${=pause} B: ${=paused-for-cache} I: ${=core-idle} VB: ${=video-bitrate:0} AB: ${=audio-bitrate:0} /home/zihad/files/torrents/One.Piece.E1061.720p.WEB-DL.AAC2.0.H.264-ThreePiece.mkv

 (+) Video --vid=1 (*) 'Japanese [Uncut]' (h264 1280x720 23.976fps)
 (+) Audio --aid=1 --alang=jpn (aac 2ch 44100Hz)
 (+) Subs  --sid=1 --slang=eng (*) 'English' (ass)
[ao/pipewire] Could not connect to context '(null)': Host is down

```

**Comment by tazihad** [comment] 2023-05-27 18:46
@smplayer-dev sdk5.12 is working. I can play av1 now.
https://github.com/smplayer-dev/smplayer/releases/download/v22.7.0-10244/smplayer-22.7.0.10129-sdk5.12.flatpak

**Comment by smplayer-dev** [comment] 2023-05-28 10:40
Please check if the problem is fixed in this build (the artifact at the bottom):
https://github.com/smplayer-dev/flatpak-builds/actions/runs/5103674066

**Comment by tazihad** [comment] 2023-05-28 11:15
> Please check if the problem is fixed in this build (the artifact at the bottom): https://github.com/smplayer-dev/flatpak-builds/actions/runs/5103674066

This build is working too.

**Closed as completed** 2023-10-23 01:54 UTC
