### ISSUE TITLE
Outdated org.kde.Platform

### ISSUE THREAD

**Issue by binnih** [flathub/info.smplayer.SMPlayer#1] opened 2022-04-08 09:01 UTC
Info: org.kde.Platform//5.12 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Plaform and SDK
Applications using this runtime:
   info.smplayer.SMPlayer

**Comment by smplayer-dev** [comment] 2022-04-08 11:22
Unfortunately org.kde.Platform//5.15 is very buggy.

**Comment by binnih** [comment] 2022-04-08 11:31
Hmm ok, well can't wait until I can get rid of that error message :)

**Comment by Erick555** [comment] 2022-04-08 12:06
org.kde.Platform//5.15 is outdated as well. Currently supported are 5.15-21.08 or 6.2

**Comment by smplayer-dev** [comment] 2022-04-08 12:25
Unfortunately the main problem is still not fixed in 5.15-21.08.
Anyway you can get a package built with 5.15-21.08 here:
https://github.com/smplayer-dev/smplayer/releases/download/v22.2.0/smplayer-22.2.0-sdk5.15.flatpak

**Comment by hfiguiere** [comment] 2022-04-08 12:37
what problem are you having with 5.15-21.08?

**Comment by Erick555** [comment] 2022-04-08 14:33
I see this app was actually [downgraded](https://github.com/flathub/info.smplayer.SMPlayer/commit/f7b76f5464a9ce623a7d947e7e0de325768b0be8) to 5.12 some time ago. Can't find any trace behind this.

I briefly tested version linked above and didn't find issues with playing video.

**Comment by smplayer-dev** [comment] 2022-04-08 21:23
> what problem are you having with 5.15-21.08?

Opengl doesn't work at all in my computer when using 5.15. It works fine with 5.12. I also experienced crashes in the open file dialog with 5.15.

**Comment by Erick555** [comment] 2022-04-08 22:51
Is it something reproducible? What's your gpu? I tested vaapi playback and it worked fine. The open file dialog comes from the host so the runtime version shouldn't affect its behavior.

I think you may consider pushing 5.15-21.08 at least in `beta` to make it available for wider testing. 5.12 is so ancient that it may not support latest hardware (mesa is over 4 years old there). Without a way forward this app would die here.

**Comment by hfiguiere** [comment] 2022-04-09 02:00
I have submitted #2  It's draft until it gets tested.

**Closed as completed** 2022-04-09 08:01 UTC

**Comment by smplayer-dev** [comment] 2022-04-09 16:35
> Is it something reproducible? What's your gpu? I tested vaapi playback and it worked fine. 

If I compile smplayer with opengl support it crashes on startup with a "Could not initialize GLX" error. The problem seems to happen to most Qt applications that use opengl. For example it also happens with shotcut:

```
$ flatpak run org.shotcut.Shotcut
Gtk-Message: 18:23:32.520: Failed to load module "unity-gtk-module"
Gtk-Message: 18:23:33.139: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:23:33.158: Failed to load module "canberra-gtk-module"
[Info   ] <Application::Application> Starting Shotcut version 22.03.30 
[Info   ] <Application::Application> Linux version 
[Info   ] <Application::Application> number of logical cores = 2 
[Info   ] <Application::Application> locale = QLocale(Spanish, Latin, Spain) 
[Info   ] <Application::Application> install dir = "/app/bin" 
[Debug  ] <ShotcutSettings::log> language "es_ES" 
[Debug  ] <ShotcutSettings::log> deinterlacer "onefield" 
[Debug  ] <ShotcutSettings::log> external monitor "" 
[Debug  ] <ShotcutSettings::log> GPU processing false 
[Debug  ] <ShotcutSettings::log> interpolation "bilinear" 
[Debug  ] <ShotcutSettings::log> video mode "" 
[Debug  ] <ShotcutSettings::log> realtime true 
[Debug  ] <ShotcutSettings::log> audio channels 2 
[Debug  ] <MainWindow::changeTheme> begin 
[Debug  ] <MainWindow::MainWindow> begin 
[Info   ] <MainWindow::MainWindow> device pixel ratio = 1 
[Fatal  ] <> Could not initialize GLX
```
Maybe in version 5.15 of the SDK they forgot to provide a library or something needed for my graphic card (ATI Radeon).

**Comment by hfiguiere** [comment] 2022-04-09 18:15
Shotcut uses 5.15-21.08.

**Comment by smplayer-dev** [comment] 2022-04-09 21:09
Yes, so unfortunately the bug is still not fixed in 5.15-21.08.

**Comment by Erick555** [comment] 2022-04-09 21:15
I can reproduce this if I remove `org.freedesktop.Platform.GL.default//21.08`. Please check if you have it installed - if not please install. It should be installed automatically with runtime or any app from flathub but maybe something prevents it on your system.

**Comment by smplayer-dev** [comment] 2022-04-10 07:43
Yes, it's already installed. Maybe they didn't add a driver for my graphic card or something.

**Comment by Erick555** [comment] 2022-04-10 20:02
You may report it [here](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues) and provide exact ati card model (Is it very old?).

**Comment by andrevmatos** [comment] 2023-10-05 13:23
This is again a problem, with `org.kde.Platform//5.15-21.08` being end-of-life.

**Comment by smplayer-dev** [comment] 2023-10-05 13:57
What's the latest version?

**Comment by andrevmatos** [comment] 2023-10-05 14:01
`org.kde.Platform//5.15-22.08` for the qt5 series, `org.kde.Platform//6.5` for the qt6 series (if smplayer can run with it).

**Comment by smplayer-dev** [comment] 2023-10-06 14:22
Please check this package:
https://github.com/smplayer-dev/smplayer/releases/download/v23.6.0.10168/smplayer-23.6.0.10168-sdk5.15.flatpak

**Comment by andrevmatos** [comment] 2023-10-06 14:25
It seems to be working, and the warning about the outdated platform is gone from my `flatpak update`; thank you

**Comment by repsorp** [comment] 2024-04-27 13:13
Message is back...
```
Info: runtime org.kde.Platform branch 5.15-22.08 is end-of-life, with reason:
   We strongly recommend moving to the latest Qt 5.15-based stable version of the Platform and SDK
Info: applications using this runtime:
   info.smplayer.SMPlayer
```
SMPlayer
Version: 23.12.0 (revision 10207)
Using Qt 5.15.10 (compiled with Qt 5.15.10)
Using MPV 0.35.1

**Comment by smplayer-dev** [comment] 2024-05-07 11:59
I'll try to update but there are some problems:
https://github.com/flathub/info.smplayer.SMPlayer/pull/8#issuecomment-1872108365
